version: 2.1

executors:
  go-executor:
    docker:
      - image: golang:1.22
    working_directory: /go/src/github.com/SahilSyed01/service

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Set up Go modules
          command: go mod tidy
      - run:
          name: Build Go application
          command: go build -o myapp

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Set execute permission on deploy.sh
          command: chmod +x ./deploy.sh
      - run:
          name: Deploy to EC2
          command: ./deploy.sh

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
