version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.22
    steps:
      - checkout
      - run: go version
      - run: go build -o output_name main.go
  test:
    docker:
      - image: golang:1.22
    steps:
      - checkout
      - run: go test ./... -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
