version: 2.1

executors:
  go-executor:
    docker:
      - image: circleci/golang:1.22  # Specify the Go version you use
    working_directory: ~/repo

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Set up Go Modules
          command: go mod download
      - run:
          name: Build Go Application
          command: go build -o myapp main.go
      - run:
          name: Run Tests
          command: go test ./...

  deploy:
    docker:
      - image: circleci/python:3.8  # Python for SSH
    steps:
      - checkout
      - run:
          name: Install SSH Client
          command: |
            apt-get update && apt-get install -y ssh
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i $EC2_SSH_KEY ec2-user@$EC2_PUBLIC_IP << 'EOF'
              sudo systemctl stop myapp || true
              mkdir -p /home/ec2-user/myapp
              cp ~/repo/myapp /home/ec2-user/myapp/
              sudo systemctl start myapp
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
