version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.22  # Use an appropriate Go version
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            go mod download

      - run:
          name: Run tests
          command: |
            go test ./...

      - run:
          name: Build the Go binary
          command: |
            go build -o service

      - run:
          name: Package the build files
          command: |
            tar -czvf service-files.tar.gz service

      - run:
          name: Deploy to S3
          command: |
            aws s3 cp service-files.tar.gz s3://${S3_BUCKET_NAME}/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
