version: 2.1

executors:
  go-executor:
    docker:
      - image: golang:1.22
    working_directory: /go/src/github.com/SahilSyed01/service

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Set up Go modules
          command: go mod tidy
      - run:
          name: Build Go application
          command: go build -o myapp

  test:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test -v ./...

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Decode and Save PEM File
          command: |
            echo $EC2_SSH_KEY | base64 -d > /tmp/your-key.pem
            chmod 600 /tmp/your-key.pem
      - run:
          name: Deploy to EC2
          command: |
            scp -i /tmp/your-key.pem -o StrictHostKeyChecking=no myapp ec2-user@$EC2_PUBLIC_IP:~/my-go-app/
            ssh -i /tmp/your-key.pem -o StrictHostKeyChecking=no ec2-user@$EC2_PUBLIC_IP "cd ~/my-go-app && nohup ./myapp &"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
