version: 2.1

executors:
  go-executor:
    docker:
      - image: golang:1.22
    working_directory: /go/src/github.com/your-repo/your-service

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: go mod download
      - run:
          name: Run Tests
          command: go test ./...
      - run:
          name: Build Application
          command: go build -o your-service

  deploy:
    docker:
      - image: atlassian/default-image:2
    steps:
      - run:
          name: Save SSH Key
          command: |
            echo "$EC2_SSH_KEY" > /tmp/id_rsa
            chmod 600 /tmp/id_rsa
      - run:
          name: Deploy Application
          command: |
            ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ec2-user@$EC2_PUBLIC_IP << 'EOF'
              sudo systemctl stop myapp || true
              mkdir -p /home/ec2-user/myapp
              cp /home/ec2-user/your-service /home/ec2-user/myapp/your-service
              sudo systemctl start myapp
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
