version: 2.1

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    docker:
      - image: golang:1.22
    steps:
      - checkout
      - run:
          name: Set up Go modules
          command: go mod tidy
      - run:
          name: Build Go application
          command: go build -o myapp
      - run:
          name: Install tar
          command: apk add --no-cache tar
      - run:
          name: Package the application
          command: tar -czvf myapp.tar.gz myapp
      - persist_to_workspace:
          root: .
          paths:
            - myapp.tar.gz

  deploy:
    docker:
      - image: amazon/aws-cli:2.4.0
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Verify AWS CLI installation
          command: aws --version
      - run:
          name: Deploy to S3
          command: aws s3 cp /workspace/myapp.tar.gz s3://${S3_BUCKET_NAME}/
