version: 2.1

executors:
  deploy-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: /go/src/github.com/SahilSyed01/service

jobs:
  deploy:
    executor: deploy-executor
    steps:
      - checkout
      - run:
          name: Set execute permission on deploy.sh
          command: chmod +x ./deploy.sh
      - run:
          name: Deploy to EC2
          command: ./deploy.sh

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
