version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.22
    steps:
      - checkout
      - run: go version
      - run: go build -o output_name main.go

  test:
    docker:
      - image: golang:1.22
    steps:
      - checkout
      - run: go test ./... -v

  deploy:
    docker:
      - image: circleci/python:3.8  # Python image for SSH utilities
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:5kclgqGWDuvEVZzelvP+ASIEU/UmtFQi5XC9q7JvcXs"  # Replace with your SSH key fingerprint from CircleCI
      - checkout
      - run:
          name: Deploy Web Service
          command: |
            INSTANCE_IP="34.201.63.192" # Your EC2 instance IP
            scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa output_name ec2-user@$INSTANCE_IP:/home/ec2-user/
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$INSTANCE_IP "sudo mv /home/ec2-user/output_name /usr/local/bin/ && sudo systemctl restart my-web-service"

workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
