version: 2.1

executors:
  go-executor:
    docker:
      - image: golang:1.22
    working_directory: /go/src/github.com/SahilSyed01/service

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Set up Go modules
          command: go mod tidy
      - run:
          name: Build Go application
          command: go build -o /workspace/myservice 

  test:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test -v ./...

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Save PEM Key File
          command: |
            echo "$EC2_SSH_KEY" | tee /tmp/your-key.pem > /dev/null
            chmod 600 /tmp/your-key.pem
            
      - run:
          name: Deploy to EC2
          command: ./deploy.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
