version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.22
    steps:
      - checkout
      - run: go version
      - run: go build -o output_name main.go

  test:
    docker:
      - image: golang:1.22
    steps:
      - checkout
      - run: go test ./... -v

  deploy:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:wzMiDgN/K58LkTcCx4KitUbtkHn0Sd29j+qcxBHxlkwt"  # Replace with your SSH key fingerprint from CircleCI
      - checkout
      # - run:
      #     name: Clone Terraform Repo
      #     command: |
      #       git clone https://github.com/SahilSyed01/infra.git
      #       cd infra
      #       terraform init
      #       terraform apply -auto-approve
      - run:
          name: Deploy Web Service
          command: |
            cd infra
            export INSTANCE_IP=$(terraform output -raw instance_ip)
            scp -i ~/.ssh/id_rsa output_name ubuntu@$INSTANCE_IP:/home/ubuntu/
            ssh -i ~/.ssh/id_rsa ubuntu@$INSTANCE_IP "sudo mv /home/ubuntu/output_name /usr/local/bin/ && sudo systemctl restart my-web-service"

workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
