version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.20
    working_directory: /go/src/github.com/SahilSyed01/service

    steps:
      - checkout

      - run:
          name: Download Dependencies
          command: go mod download

      - run:
          name: Run Tests
          command: go test ./...

      - run:
          name: Build Application
          command: go build -o your-service

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
