version: 2.1

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    docker:
      - image: golang:1.22
    steps:
      - checkout
      - run:
          name: Set up Go modules
          command: go mod tidy
      - run:
          name: Build Go application
          command: go build -o myapp
      - run:
          name: Package the application
          command: tar -czvf myapp.tar.gz myapp

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Install awscli
          command: |
            curl "https://d1uj6qtbmh3dt5.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            if [ -f awscliv2.zip ]; then
              unzip awscliv2.zip
              sudo ./aws/install
            else
              echo "Failed to download AWS CLI package."
              exit 1
            fi
      - run:
          name: Deploy to S3
          command: aws s3 cp myapp.tar.gz s3://${S3_BUCKET_NAME}/
