version: 2.1

jobs:
  build_and_push_image:
    docker:
      - image: docker:20.10.7 # Use Docker for the build job
    steps:
      - checkout # Check out the code from GitHub
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Install AWS CLI
          command: |
            apk add --no-cache py3-pip
            pip3 install awscli
      - run:
          name: Log in to AWS ECR
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO_URL
      - run:
          name: Build Docker Image
          command: |
            docker build -t $ECR_REPO_URL:latest .
      - run:
          name: Push Docker Image
          command: |
            docker push $ECR_REPO_URL:latest

workflows:
  build_and_push:
    jobs:
      - build_and_push_image
