version: 2.1

executors:
  go-executor:
    docker:
      - image: circleci/golang:1.18

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go mod download
      - run:
          name: Build the Go application
          command: go build -o /workspace/myservice ./cmd/myservice
      - persist_to_workspace:
          root: /workspace
          paths:
            - myservice

  deploy:
    executor: go-executor
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy to EC2
          command: |
            chmod +x ./deploy.sh
            ./deploy.sh

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
