version: 2.1

executors:
  docker-executor:
    docker:
      - image: golang:1.22

  docker-with-docker:
    docker:
      - image: docker:20.10.7
    # `setup_remote_docker` should be defined in the job, not the executor

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Build Go Application
          command: |
            go mod download
            go build -o service main.go

  deploy_to_s3:
    docker:
      - image: amazonlinux:2
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            yum install -y python3
            pip3 install awscli
      - run:
          name: Deploy to S3
          command: |
            aws s3 sync ./ s3://unique-service-files-bucket-12345 --delete

  build_and_push_image:
    docker:
      - image: docker:20.10.7
    setup_remote_docker:
      version: 20.10.7
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            apk add --no-cache py3-pip
            pip3 install awscli
      - run:
          name: Log in to AWS ECR
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO_URL
      - run:
          name: Build Docker Image
          command: |
            docker build -t $ECR_REPO_URL:latest .
      - run:
          name: Push Docker Image
          command: |
            docker push $ECR_REPO_URL:latest

workflows:
  build_deploy_and_push:
    jobs:
      - build
      - deploy_to_s3:
          requires:
            - build
          filters:
            branches:
              only: main
      - build_and_push_image:
          requires:
            - build
          filters:
            branches:
              only: main
