version: 2.1

executors:
  docker-executor:
    docker:
      - image: golang:1.22

jobs:
  build_and_deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Build Go Application
          command: |
            go mod download
            go build -o service main.go
      - run:
          name: Install AWS CLI
          command: |
            apk add --no-cache py3-pip
            pip3 install awscli
      - run:
          name: Deploy Go Application to S3
          command: |
            aws s3 sync ./ s3://unique-service-files-bucket-12345 --delete
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Log in to AWS ECR
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO_URL
      - run:
          name: Build Docker Image
          command: |
            docker build -t $ECR_REPO_URL:latest .
      - run:
          name: Push Docker Image
          command: |
            docker push $ECR_REPO_URL:latest

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: main
