version: 2.1

executors:
  go-executor:
    docker:
      - image: circleci/golang:1.19
    working_directory: /go/src/github.com/your-repo/your-service

jobs:
  build:
    executor: go-executor
    steps:
      - checkout

      - run:
          name: Download Dependencies
          command: go mod download

      - run:
          name: Run Tests
          command: go test ./...

      - run:
          name: Build Application
          command: go build -o your-service

  deploy:
    docker:
      - image: circleci/python:3.8  # Python for SSH
    steps:
      - checkout
      - run:
          name: Install SSH Client
          command: |
            apt-get update && apt-get install -y ssh
      - run:
          name: Create Deployment Script
          command: |
            echo '#!/bin/bash' > deploy.sh
            echo 'sudo systemctl stop your-service || true' >> deploy.sh
            echo 'mkdir -p /home/ec2-user/your-service' >> deploy.sh
            echo 'cp ~/repo/your-service /home/ec2-user/your-service/' >> deploy.sh
            echo 'sudo systemctl start your-service' >> deploy.sh
            chmod +x deploy.sh
      - run:
          name: Deploy to EC2
          command: |
            scp -o StrictHostKeyChecking=no -i $EC2_SSH_KEY deploy.sh ec2-user@$EC2_PUBLIC_IP:/home/ec2-user/
            ssh -o StrictHostKeyChecking=no -i $EC2_SSH_KEY ec2-user@$EC2_PUBLIC_IP 'bash /home/ec2-user/deploy.sh'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
