version: 2.1

executors:
  go-executor:
    docker:
      - image: golang:1.22
    working_directory: /go/src/github.com/SahilSyed01/service

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Set up Go modules
          command: go mod tidy
      - run:
          name: Build Go application
          command: go build -o myapp
      - persist_to_workspace:
          root: /go/src/github.com/SahilSyed01/service
          paths:
            - myapp

  test:
    executor: go-executor
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Run tests
          command: go test -v ./...

  package:
    executor: go-executor
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Package the application
          command: tar -czvf /workspace/myapp.tar.gz /workspace/myapp

  deploy_s3:
    docker:
      - image: circleci/python:3.8
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: List workspace files
          command: ls -la /workspace

      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Deploy to S3
          command: aws s3 cp /workspace/myapp.tar.gz s3://${S3_BUCKET_NAME}/

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - package:
          requires:
            - test
      - deploy_s3:
          requires:
            - package
